services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  distributedcache:
    image: redis

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: src/Services/Catalog.Api/Dockerfile
  
  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.Api/Dockerfile

  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket: