global using Carter;
global using Mapster;
global using MediatR;
global using BuildingBlocks.Cqrs;
global using Marten;
global using Catalog.Api.Models;
global using Catalog.Api.Exceptions;
global using FluentValidation;
global using BuildingBlocks.Exceptions;